HeadNode:
  InstanceType: c5.large
  Ssh:
    KeyName: <ssh-key>
  Networking:
    SubnetId: <PrivateSubnet1 from OOD Stack Output>
    AdditionalSecurityGroups:
      - <HeadNodeSecurityGroup>
  LocalStorage:
    RootVolume:
      VolumeType: gp3
      Size: 50
  Iam:
    AdditionalIamPolicies:
      - Policy: <HeadNodeSecurityGroup from CloudFormation Outputs
      - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
      - Policy: >-
          <HeadNodeIAMPolicyArn from CloudFormation Outputs>
  CustomActions:
    OnNodeConfigured:
      Script: >-
        s3://openondemand-clusterconfigbucket-xxxxx/pcluster_head_node.sh
      Args:
        - OpenOnDemand
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: general
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: general-cr
          Instances:
            - InstanceType: c5n.large
          MinCount: 0
          MaxCount: 4
      Networking:
        SubnetIds:
          - <PrivateSubnet1 from OOD Stack Output>
        AdditionalSecurityGroups:
          - <ComputeNodeSecurityGroup from CloudFormation Outputs>
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
            Size: 50
      CustomActions:
        OnNodeConfigured:
          Script: >-
            s3://openondemand-clusterconfigbucket-xxxxx/pcluster_worker_node.sh
          Args:
            - <OpenOnDemand CloudFormation stack name>
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
          - Policy: >-
              <ComputeNodeIAMPolicyArn from CloudFormation Outputs>
    - Name: desktop
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: desktop-cr
          Instances:
            - InstanceType: c5n.2xlarge
          MinCount: 0
          MaxCount: 10
      Networking:
        SubnetIds:
          - <PrivateSubnet1 from OOD Stack Output>
        AdditionalSecurityGroups:
          - <ComputeNodeSecurityGroup from CloudFormation Outputs>
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
            Size: 50
      CustomActions:
        OnNodeConfigured:
          Script: >-
            s3://openondemand-clusterconfigbucket-xxxxx/pcluster_worker_node_desktop.sh
          Args:
            - <OpenOnDemand CloudFormation stack name>
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
          - Policy: >-
              <ComputeNodeIAMPolicyArn from CloudFormation Outputs>
  SlurmSettings: {}
Region: us-east-1
Image:
  Os: alinux2
DirectoryService:
  DomainName: dc=hpclab,dc=local
  DomainAddr: "<LDAPNLBEndPoint from CloudFormation outputs>"
  PasswordSecretArn: "<ADAdministratorSecretARN from CloudFormation outputs>"
  DomainReadOnlyUser: cn=Admin,ou=Users,ou=hpclab,dc=hpclab,dc=local
